;DATA SEGMENT IS DEFINED 
MY_DATA SEGMENT PARA 'DATA'
    NAME1 DB 'HELLO'
    NUM DW ?
    LIST1 DB  2 DUP(3), 3 DUP(2) 
    LIST2 DB  3 DUP(1),2 DUP(?)
MY_DATA ENDS

MY_CODE SEGMENT PARA 'CODE'
MY_PROG PROC FAR

        MOV AX,MY_DATA
        MOV DS,AX
 
       
;IMMEDIATE ADDRESSING
        MOV NUM,200
        MOV AX,0ABCDH


;REGISTER ADDRESSING
        MOV DH,AL          


;DIRECT ADDRESSING
        MOV NUM,AX
        MOV DL,LIST1 


;REGISTER INDIRECT ADDRESSING
        MOV BX, OFFSET LIST2
        MOV CX,[BX]        


;BASE INDEXED ADDRESSING
        MOV DI,1
        MOV BX, OFFSET LIST1
        MOV AL, [BX][DI]+3
        MOV BX,2
        MOV AH, LIST1[BX][DI]
        MOV LIST2[BX+DI],0FFH 
          

;DIRECT INDEXED ADRESSING
	  MOV DI,2
	  MOV CL,LIST1[DI]
	  MOV LIST2[DI],3 			


;BASE RELATIVE ADDRESSING
	  MOV BX,OFFSET LIST2
      MOV AX,[BX+2]


      MOV AH, 04CH
      INT 21H
        
        RET
MY_PROG ENDP
MY_CODE ENDS
        END MY_PROG
